[PR-15477] Integration documentation for Loyalty
talkable/talkable-docs pull request #241
Opened 2021-03-31 21:40 UTC by dgtv

## Demo

https://deploy-preview-241--talkable-docs.netlify.app/

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-15477)](https://talkable.atlassian.net/browse/PR-15477)

2021-04-01 16:57 UTC, zhuravel requested changes

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +3. :ref:`Loyalty Redeem Widget <integration/loyalty/integration_components/loyalty_redeem_widget>`
```suggestion
2. :ref:`Loyalty Dashboard`

3. :ref:`Loyalty Redeem Widget`
```

https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-sections-in-the-same-document

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +   template in order for the loyalty dashboard to work
```suggestion
1. The `Talkable Initialization Script <Initialization Script_>`_ must be
   present in your head template in order for the Loyalty Dashboard to work.
```

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +2. **Variables.** Use your dynamic variables to pass user details
```suggestion
2. **Variables.** Use your dynamic variables to pass user details.
```

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty.rst
> +   It is recommended to upload 100K single-use coupons into every coupon list.
Non-technical people might not know that K represents thousand.
```suggestion
   It is recommended to upload 100,000 single-use coupons into every coupon list.
```

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +.. _integration/loyalty/integration_components/loyalty_dashboard:
```suggestion
.. _Loyalty Dashboard:
```

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +.. _integration/loyalty/integration_components/loyalty_redeem_widget:
```suggestion
.. _Loyalty Redeem Widget:
```

2021-04-01 16:57 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +1. :ref:`Initialization Script <integration/loyalty/integration_components/initialization_script>`
```suggestion
1. `Initialization Script <Initialization Script_>`_
```

2021-04-01 17:08 UTC, zhuravel commented on source/integration/loyalty/integration_components.rst
> +   **Data Capture** The Initialization Script should pass variables for logged in users:
@dgtv Please fix original as well ↑

2021-04-01 17:27 UTC, zhuravel approved these changes

2021-04-02 08:20 UTC, zhuravel reviewed
The only way to make _Integration Components_ not nested under _Requirements_ is to not add _Integration_ and _Requirements_ to tree:

![2021-04-02 11-18-49](https://user-images.githubusercontent.com/1140581/113397154-43b8bf00-93a5-11eb-8f07-26f4515a4cdf.png)

2021-04-02 08:20 UTC, zhuravel commented on source/integration/loyalty.rst
> +-----------
```suggestion
.. raw:: html

   <h2>Integration</h2>
```

2021-04-02 08:20 UTC, zhuravel commented on source/integration/loyalty.rst
> +------------
```suggestion
.. raw:: html

   <h2>Requirements</h2>
```

2021-04-02 08:29 UTC, dgtv commented on source/integration/loyalty.rst
> +------------
👍 Cool, thanks

2021-04-02 08:31 UTC, zhuravel approved these changes

2021-04-09 11:53 UTC, merged