[PR-17382] Add sharer_info to Post-Share Webhook
talkable/talkable-docs pull request #261
Opened 2021-11-24 15:04 UTC by hmlON

## Screenshots
![image](https://user-images.githubusercontent.com/3994897/143262622-1bc8e93d-857c-494f-9916-d36fee55b482.png)
![image](https://user-images.githubusercontent.com/3994897/143262683-d54d959e-bebe-408c-90df-3ad4e946d636.png)

## Demo

https://void-docs.talkable.com/web_hooks/post_share.html

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-17382)](https://talkable.atlassian.net/browse/PR-17382)

2021-11-24 15:22 UTC, zhuravel requested changes

2021-11-24 15:22 UTC, zhuravel commented on source/web_hooks/post_share.rst
> +Note: origin email is the email at the time when the campaign is first shown to the visitor, please, use sharer info for the most up to date information
* Use `..note:` directive.
* We can elaborate on this, please approve the text with Stacey if you proceed with this suggestion.
```suggestion
.. note::

   ``origin.email`` contains the email saved at the moment when the campaign is 
   first shown to the Advocate. It could be ``null``. For the most up-to-date 
   information about the Advocate, use ``sharer_info`` property which is updated
   with the email address the Advocate has entered on the Advocate Signup Page.

2021-11-24 15:22 UTC, zhuravel commented on source/web_hooks/post_share.rst
> +* **sharer_info** — subhash of parameters describing the person sending the share
```suggestion
* **sharer_info** — subhash of parameters describing the person who shared the offer
```

2021-11-25 11:15 UTC, hmlON commented on source/web_hooks/post_share.rst
> +Note: origin email is the email at the time when the campaign is first shown to the visitor, please, use sharer info for the most up to date information
The new text was approved with Stacey

2021-11-25 11:16 UTC, zhuravel approved these changes

2021-11-25 11:27 UTC, zhuravel commented on source/web_hooks/post_share.rst
>         "id": 147886587,
@hmlON There’s no `origin.email` here, please fix the example.

2021-11-25 11:28 UTC, zhuravel requested changes
Also, update cURL example below.

2021-11-25 11:41 UTC, zhuravel requested changes
cURL example not updated.

2021-11-25 11:45 UTC, zhuravel requested changes
No `sharer_info` in cURL example.

2021-11-25 11:50 UTC, hmlON commented
@zhuravel Do we need to include deprecated fields (`order_date`) in the example payload?

2021-11-25 11:53 UTC, zhuravel commented
@hmlON Yes, and we should mark them as deprecated. See `subscribed_at` in `person_fields.rst`:
https://github.com/talkable/talkable-docs/blob/45363e2437fb0c988cf7478c2908646d1035ad1c/source/partials/person_fields.rst#L7-L6

2021-11-25 13:32 UTC, zhuravel approved these changes

2021-11-25 13:32 UTC, zhuravel commented on source/web_hooks/post_share.rst
> +       "order_date":"2019-04-11T07:28:31.258-07:00",
```suggestion
       "order_date": "2019-04-11T07:28:31.258-07:00",
```

2021-11-30 14:34 UTC, merged