[PR-17629] Accept phone number as a request parameter
talkable/talkable-docs pull request #263
Opened 2022-02-07 12:47 UTC by hmlON

Main PR - https://github.com/talkable/talkable/pull/8191

## Demo

https://void-docs.talkable.com/

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-17629)](https://talkable.atlassian.net/browse/PR-17629)

2022-02-07 14:29 UTC, zhuravel requested changes
Please update APIv2 sample responses and cURL examples.

2022-02-07 14:29 UTC, zhuravel commented on source/advanced_features/params_encryption.rst
> +       phone_number: '<%= to_json(current_user.phone_number) %>',
```suggestion
       phone_number: '<%= to_json(TalkableEncryptionService.encrypt(current_user.phone_number)) %>,
```

2022-02-08 13:45 UTC, zhuravel approved these changes
You can add `phone_number` here:
https://github.com/talkable/talkable-docs/blob/d838a96dbc0fb6981e7556fcac9de6990f5f1d28/source/samples/ecommerce/platform/shopify_init_script.rst#L9-L13
```js
_talkableq.push(['authenticate_customer', {
  email:        '{{ customer.email }}',
  phone_number: '{{ customer.phone }}',
  first_name:   '{{ customer.first_name }}',
  last_name:    '{{ customer.last_name }}'
}]);
```

See `customer.phone` variable:
https://shopify.dev/api/liquid/objects/customer#customer-phone

2022-02-08 14:17 UTC, hmlON commented
@zhuravel `customer.phone` is already [there](https://github.com/talkable/talkable-docs/blob/kholin-PR-17629/source/samples/ecommerce/platform/shopify_init_script.rst#L9-L13)

2022-02-08 14:18 UTC, zhuravel approved these changes

2022-04-14 09:10 UTC, merged