PR-18042 Add currency as require attribute for multi-currency sites
talkable/talkable-docs pull request #270
Opened 2022-04-29 13:29 UTC by imnastasia

## Demo

https://deploy-preview-{{id}}--talkable-docs.netlify.app/

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-1234)](https://talkable.atlassian.net/browse/PR-1234)

2022-04-30 10:12 UTC, zhuravel requested changes

2022-04-30 10:12 UTC, zhuravel commented on source/web_hooks/event.rst
> +     * **currency_iso_code** - currency ISO code of the Purchase
```suggestion
     * **currency_iso_code** - currency ISO code of the Event
```

2022-04-30 10:12 UTC, zhuravel commented on source/samples/advanced_features/product_items.rst
> +        currency_iso_code: '', // It is required for multi-currency sites. Example: 'USD'
```suggestion
        currency_iso_code: '', // Required for multi-currency sites. Example: 'USD'
```

2022-04-30 10:12 UTC, zhuravel commented on source/integration/custom/integration_components.rst
> +         currency_iso_code: '', // It is required for multi-currency sites. Example: 'USD'
```suggestion
         currency_iso_code: '', // Required for multi-currency sites. Example: 'USD'
```

2022-04-30 10:12 UTC, zhuravel commented on source/integration/custom/alternate_post_purchase.rst
> +        currency_iso_code: '', // It is required for multi-currency sites. Example: 'USD'
```suggestion
        currency_iso_code: '', // Required for multi-currency sites. Example: 'USD'
```

2022-06-02 09:52 UTC, imnastasia commented on source/web_hooks/event.rst
> +       "currency_iso_code": "USD",
@zhuravel Correct me if I'm wrong, but in ParseParams we process any param inside the payload hash with 'o'/'origin' key

2022-06-02 09:54 UTC, zhuravel commented on source/web_hooks/event.rst
> +       "currency_iso_code": "USD",
@imnastasia Don’t see how `ParseParams` is related to Event Webhook.
[This serializer](https://github.com/talkable/talkable/blob/master/app/serializers/payload/event_serializer.rb) is used for the webhook and it does not contain `currency_iso_code`.

2022-06-02 10:56 UTC, imnastasia commented on source/web_hooks/event.rst
> +       "currency_iso_code": "USD",
@zhuravel oh I see. 
should I create a separate ticket to add it to the serializers and update docs, or just make a PR for adding it to the code without a separate ticket?

2022-06-02 10:57 UTC, zhuravel commented on source/web_hooks/event.rst
> +       "currency_iso_code": "USD",
@imnastasia 2

2022-06-02 11:32 UTC, zhuravel approved these changes

2022-06-02 13:27 UTC, merged