[PR-16730] SPM distribution documentation for iOS SDK and polishing
talkable/talkable-docs pull request #275
Opened 2022-07-07 20:37 UTC by dgtv

Documentation update for https://github.com/talkable/ios-sdk/pull/16

## Demo

https://deploy-preview-275--talkable-docs.netlify.app/

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-16730)](https://talkable.atlassian.net/browse/PR-16730)

2022-07-08 12:29 UTC, zhuravel requested changes

2022-07-08 12:29 UTC, zhuravel commented on source/ios_sdk/getting_started.rst
> +            <string>tkbl-<your-site-id></string>
@dgtv There are more places where slug is still slug:

<img width="1444" alt="2022-07-08 15-28-05" src="https://user-images.githubusercontent.com/1140581/177992239-4a452e53-65d0-47a9-ba4f-38a0bc8b4e30.png">

2022-07-08 13:25 UTC, dgtv commented on source/ios_sdk/getting_started.rst
> +            <string>tkbl-<your-site-id></string>
Ok, I'll remove changes related to `site_slug` from this PR and will introduce them along this task  https://talkable.atlassian.net/browse/PR-18436 and PR https://github.com/talkable/talkable/pull/8512 as it also requires such changes anyway.

2022-07-13 08:22 UTC, zhuravel approved these changes

2022-07-13 08:22 UTC, zhuravel commented on source/ios_sdk/getting_started.rst
> +        <string>tkbl-<your-site-slug></string>
Let’s use some other placeholder format that does not look like XML tag in an XML snippet and does not make it seem invalid (no closing tag).
```suggestion
        <string>tkbl-YOUR-SITE-SLUG</string>
```

2022-07-13 08:22 UTC, zhuravel commented on source/ios_sdk/integration/post_purchase.rst
> +Post Purchase campaign usually looks like a pop up right after a user made a purchase. This campaign is initialized on the order confirmation page and captures order with it's details. You need to pa
https://boldomatic.com/p/xj2qSA/you-re-you-fucking-are-your-shows-fucking-possession-they-re-they-fucking-are-th

```suggestion
Post Purchase campaign usually looks like a pop up right after a user made a purchase. This campaign is initialized on the order confirmation page and captures order with its details. You need to pass order data to Talkable that includes your customer’s email address, order number, subtotal, coupon code used at checkout to allow Talkable detect and close a referral loop.
```

2022-07-13 08:22 UTC, zhuravel commented on source/ios_sdk/integration/standalone.rst
> +        @"eye_color": @"green"
Just wondering – what made you change this?

2022-07-13 09:28 UTC, dgtv commented on source/ios_sdk/integration/standalone.rst
> +        @"eye_color": @"green"
Just read text above =)
> For example, below we are creating and passing a custom key value pair of *eye color* = *green*. Any data passed through here will be accessible on a campaign level for segmentation or other logic.

2022-07-13 09:50 UTC, zhuravel approved these changes

2022-07-18 11:31 UTC, zhuravel approved these changes

2022-07-18 11:31 UTC, zhuravel commented on source/ios_sdk/api_integration.rst
> +   //...
```suggestion
   // ...
```

2022-07-19 13:25 UTC, merged