[PR-19186] Webhook Payload
talkable/talkable-docs pull request #294
Opened 2023-01-11 10:11 UTC by imnastasia

Main PR [#8799](https://github.com/talkable/talkable/pull/8799)
## Demo

https://deploy-preview-{{id}}--talkable-docs.netlify.app/

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-19186)](https://talkable.atlassian.net/browse/PR-19186)

2023-01-11 11:43 UTC, dgtv commented on source/web_hooks/check_unsubscribe.rst
> +    http://talkable.local:3000/api-docs/index.html?urls.primaryName=Webhooks#/Check%20Unsubscribe%20Webhook/post_yourApiCheckUnsubscribeWebhookPath
Looks like should be removed:
```suggestion
```

2023-01-11 11:43 UTC, dgtv commented on source/web_hooks/offer_signup.rst
> +   <p><a href="https://www.talkable.com/api-docs/index.htmlurls.primaryName=Webhooks#/Advocate%20Signup%20Webhook/post_yourApiAdvocateSignUpWebhookPath">Advocate Signup Webhook Payload</a></p>
```suggestion
   <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Advocate%20Signup%20Webhook/post_yourApiAdvocateSignUpWebhookPath">Advocate Signup Webhook Payload</a></p>
```

2023-01-17 17:14 UTC, zhuravel requested changes

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/check_unsubscribe.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Check%20Unsubscribe%20Webhook/post_yourApiCheckUnsubscribeWebhookPath">Check Unsubscribe Webhook Payload</a></p
Use RST (reStructuredText) instead of HTML to add links. Examples:

https://github.com/talkable/talkable-docs/blob/71220ffd5e9feef4829feb7accc1db146e1b3bb3/source/campaigns/editor/variables.rst#L14-L15

https://github.com/talkable/talkable-docs/blob/71220ffd5e9feef4829feb7accc1db146e1b3bb3/source/android_sdk/advanced.rst#L172-L194

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/create_coupon.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Create%20Coupon%20Webhook/post_yourApiCreateCouponWebhookPath">Create Coupon Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/event.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Event%20Webhook/post_yourApiEventWebhookPath">Event Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/offer_signup.rst
> +   <p><a href="https://www.talkable.com/api-docs/index.htmlurls.primaryName=Webhooks#/Advocate%20Signup%20Webhook/post_yourApiAdvocateSignUpWebhookPath">Advocate Signup Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/post_share.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Post%20Share%20Webhook/post_yourApiPostShareWebhookPath">Post Share Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/referral.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Referral/post_yourApiReferralWebhookPath">Referral Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/reward.rst
> +    <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Reward/post_yourApiRewardWebhookPath">Reward Webhook Payload</a></p>
Same.

2023-01-17 17:14 UTC, zhuravel commented on source/web_hooks/unsubscribe.rst
> +   <p><a href="https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Unsubscribe%20Webhook/post_yourApiUnsubscribeWebhookPath">Unsubscribe Webhook Payload</a></p>
Same.

2023-02-06 16:22 UTC, zhuravel requested changes

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/check_unsubscribe.rst
> +The sample payload with parameters for Check Unsubscribe Webhook is available here: `Check Unsubscribe Webhook Payload`_.
```suggestion
The sample payload with parameters for Check Unsubscribe Webhook is available here: `Check Unsubscribe Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Check%20Unsubscribe%20Webhook/post_yourApiCheckUnsubscribeWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/check_unsubscribe.rst
>  .. raw:: html
```suggestion
.. raw:: html
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/claim_signup.rst
> +The sample payload with parameters for Friend Email Gating Webhook is availablehere: `Friend Email Gating Webhook Payload`_.
Space missing in `availablehere`.
```suggestion
The sample payload with parameters for Friend Email Gating Webhook is available here: `Friend Email Gating Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Friend%20Email%20Gating%20Webhook/post_yourApiFriendEmailGatingWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/claim_signup.rst
>  .. container:: hidden
```suggestion
.. container:: hidden
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/event.rst
>  .. container:: hidden
```suggestion
.. container:: hidden
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/post_share.rst
> +The sample payload with parameters for Post Share Coupon Webhook is available here: `Post Share Webhook Payload`_.
There is no Post Share COUPON Webhook.

```suggestion
The sample payload with parameters for Post Share Webhook is available here: `Post Share Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Post%20Share%20Webhook/post_yourApiPostShareWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/post_share.rst
>  .. note::
```suggestion
.. note::
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/referral.rst
> +The sample payload with parameters for Referral Webhook is available here: `Referral Webhook Payload`_.
```suggestion
The sample payload with parameters for Referral Webhook is available here: `Referral Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Referral/post_yourApiReferralWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/referral.rst
>  .. include:: /partials/coupon_as_reward.rst
```suggestion
.. include:: /partials/coupon_as_reward.rst
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/reward.rst
> +The sample payload with parameters for Reward Webhook is available here: `Referral Webhook Payload`_.
Please be more attentive to details. Not a REFERRAL webhook.
```suggestion
The sample payload with parameters for Reward Webhook is available here: `Reward Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Reward/post_yourApiRewardWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/reward.rst
>  .. raw:: html
```suggestion
.. raw:: html
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/unsubscribe.rst
> +The sample payload with parameters for Unsubscribe Webhook is available here: `Unsubscribe Webhook Payload`_.
```suggestion
The sample payload with parameters for Unsubscribe Webhook is available here: `Unsubscribe Webhook Payload <https://www.talkable.com/api-docs/index.html?urls.primaryName=Webhooks#/Unsubscribe%20Webhook/post_yourApiUnsubscribeWebhookPath>`_.
```

2023-02-06 16:22 UTC, zhuravel commented on source/web_hooks/unsubscribe.rst
>  .. container:: hidden
```suggestion
.. container:: hidden
```

2023-02-07 17:23 UTC, zhuravel requested changes
## Read this before re-requesting the review:

To save both our time and reduce code review cycles, please go over my previous comments one by one, read them very carefully, stopping at every one of them, and do the required changes. You’ve only changed the links, and skipped typos and copy-paste issues.

For example, I’ve said that you have a typo here:
https://github.com/talkable/talkable-docs/pull/294#discussion_r1097604670

And you have wrong webhook name here:
https://github.com/talkable/talkable-docs/pull/294#discussion_r1097608991

And also wrong webhook name here:
https://github.com/talkable/talkable-docs/pull/294#discussion_r1097612494

etc.

You would fix all of those if you just accepted my suggestions, but you fix half the issues and have another review cycle.

2023-02-08 15:06 UTC, zhuravel approved these changes

2023-02-23 08:45 UTC, merged