[PR-21380] [Shopify] Migration 2.0 theme for existing clients support
talkable/talkable-docs pull request #320
Opened 2024-01-24 12:04 UTC by Doimhneacht

## Demo

https://void-docs.talkable.com/integration/ecommerce_platforms/shopify.html#manual-integration
https://void-docs.talkable.com/integration/ecommerce_platforms/shopify.html#manual-migrating-from-a-vintage-theme-to-an-online-store-2-0-theme
https://void-docs.talkable.com/integration/loyalty/shopify_integration.html#manual-integration
https://void-docs.talkable.com/integration/loyalty/shopify_integration.html#manual-migrating-from-a-vintage-theme-to-an-online-store-2-0-theme

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-21380)](https://talkable.atlassian.net/browse/PR-21380)

2024-01-24 20:23 UTC, zhuravel approved these changes

2024-01-24 20:23 UTC, zhuravel commented on source/integration/ecommerce_platforms/shopify.rst
> +        * Optionally, update the schema name to anything meaningful, for example, “Referral campaign
```suggestion
        * Optionally, update the schema name to anything meaningful, for example, “Referral campaign“
```

2024-01-25 14:25 UTC, dgtv requested changes

2024-01-25 14:25 UTC, dgtv commented on source/integration/loyalty/shopify_integration.rst
> +6. In your Shopify Admin create resources for loyalty dashboard page:
About loyalty integration I checked with Ksyusha and she said that it will be removed soon, so we can skip it update. Sorry for the confuse

2024-01-25 14:25 UTC, dgtv commented on source/integration/ecommerce_platforms/shopify.rst
> +7. In your Shopify Admin, add the integration to your layout:
I see you removed completely instruction for "vintage" theme and don't specify that these new instructions are only applicable for 2.0 themes. But we need 2 set of instructions for both Vintage and 2.0 themes.

2024-01-25 14:43 UTC, Doimhneacht commented on source/integration/loyalty/shopify_integration.rst
> +6. In your Shopify Admin create resources for loyalty dashboard page:
It's easier to keep it since I didn't do it in a separate commit. It won't harm anyone.

2024-01-25 15:01 UTC, dgtv commented on source/integration/loyalty/shopify_integration.rst
> +6. In your Shopify Admin create resources for loyalty dashboard page:
ok, no problem, thanks

2024-01-25 15:05 UTC, Doimhneacht commented on source/integration/ecommerce_platforms/shopify.rst
> +7. In your Shopify Admin, add the integration to your layout:
Done. Please see [2.0 docs](https://void-docs.talkable.com/integration/ecommerce_platforms/shopify.html#for-shopify-online-store-2-0-themes) and [vintage docs](https://void-docs.talkable.com/integration/ecommerce_platforms/shopify.html#for-shopify-vintage-themes).

2024-01-25 16:54 UTC, dgtv approved these changes
LG, thanks!

2024-01-25 16:54 UTC, dgtv commented on source/_static/img/shopify/editor_template.png
From my experience users sometimes tend to just copy instructions without reading remarks. So I think it is better to remove "disabled: true" section from the screenshot or think about better highlight that can prevent such situations. But it is just a notice, not a requirement

2024-01-25 16:54 UTC, dgtv commented on source/integration/ecommerce_platforms/shopify.rst
> +             If your main section is disabled, remove the row that does it.
Can we please add a screenshot how final migration result should look like?

2024-02-22 13:41 UTC, merged