[PR-23094] Create integration partners pages at docs.talkable.com for rest of integrations
talkable/talkable-docs pull request #344
Opened 2024-11-05 09:45 UTC by Buritos16

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-23094)](https://talkable.atlassian.net/browse/PR-23094)

2024-11-05 18:17 UTC, dgtv requested changes
Great job!
Please remove sections for internal use and some other remarks

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/bluecore.rst
> +- Apps
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/braze.rst
> +- Apps (sync opt-ins)
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/cheetah.rst
> +- Apps
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/cordial.rst
> +- Unsubscribe
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/exponea.rst
> +- Apps
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/getresponse.rst
> +- Claim Signup
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/iterable.rst
> +- Unsubscribe
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/omnisend.rst
> +- Apps
```suggestion
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/sendgrid.rst
> +   :description: Synchronize emails Talkable collected with Sendgrid integration.
Please change wording here and in other places to make it more clear: 
```suggestion
   :description: Synchronize Talkable collected emails with Sendgrid integration.
```

2024-11-05 18:17 UTC, dgtv commented on source/email_marketing_and_automation/sfmc_dataextension.rst
> +   :description: Synchronize emails Talkable collected with SFMC DataExtension integration.
```suggestion
   :description: Synchronize Talkable collected emails with Salesforce Marketing Cloud integration.
```

2024-11-11 14:23 UTC, dgtv commented on source/advanced_features/facebook_login_share.rst
> +   :description: Integrate Facebook Login & Share with your Talkable system for enhanced user authentication and social sharing. Follow our step-by-step guide to enable the app, configure Facebook Ap
```suggestion
   :description: Integrate Facebook Login & Share with your Talkable system for enhanced user authentication and social sharing. Follow our step-by-step guide to enable the app, configure Facebook App IDs, and streamline users login and sharing processes.
```

2024-11-11 14:23 UTC, dgtv commented on source/advanced_features/tremendous.rst
> +     - A "tremendous" Liquid filter used in Reward Paid Email Page.
lets leave the filter link

2024-11-11 14:23 UTC, dgtv commented on source/custom_integration/chatgpt_text_generation.rst
> +With this integration, Talkable utilizes OpenAI's ChatGPT API to generate custom AI-driven text for AD notes or other campaign-specific purposes.
```suggestion
With this integration, Talkable utilizes OpenAI's ChatGPT API to generate custom AI-driven text for Advocate's sharing message or other campaign-specific purposes.
```

2024-11-11 17:10 UTC, Buritos16 commented on source/advanced_features/tremendous.rst
> +     - A "tremendous" Liquid filter used in Reward Paid Email Page.
@dgtv it brokes test:
https://app.circleci.com/pipelines/github/talkable/talkable-docs/1697/workflows/385fced5-6f4d-4e83-95bb-2260aad1d232/jobs/1356

2024-11-11 17:15 UTC, dgtv commented on source/advanced_features/tremendous.rst
> +     - A "tremendous" Liquid filter used in Reward Paid Email Page.
can't you just revert changes for tremendous here and in filters section? because master is green

2024-11-15 03:15 UTC, dgtv commented on source/custom_integration/chatgpt_text_generation.rst
> +==========================
Let's make integrations names general
```suggestion
ChatGPT
=======
```

2024-11-15 03:15 UTC, dgtv commented on source/custom_integration/crowdtwist.rst
> +=============================
```suggestion
CrowdTwist
==========
```

2024-11-15 03:15 UTC, dgtv commented on source/custom_integration/chatgpt_text_generation.rst
and lets rename the file

2024-11-15 03:15 UTC, dgtv commented on source/custom_integration/listrak_sms.rst
> +===========
There is no need to have 2 pages for Listrak integration: SMS and opt-in. Please incorporate SMS integtation into regular Listrak page you created.

2024-11-20 19:40 UTC, dgtv approved these changes
Great job!

2024-11-27 10:35 UTC, merged