[PR-23265][Custom app] Create public documentation
talkable/talkable-docs pull request #349
Opened 2024-11-26 20:58 UTC by wrimer

## Demo

https://void-docs.talkable.com/email_marketing_and_automation/custom_app.html

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-23265)](https://talkable.atlassian.net/browse/PR-23265)

2024-11-27 12:49 UTC, zhuravel requested changes

2024-11-27 12:49 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +   * 54.91.51.228
Please do not duplicate IPs in documentation and link to existing list instead.
Either that or move list to partial / separate page.
Either way there should only be a single place we’re updating.
https://github.com/talkable/talkable-docs/blob/f8e68648654d7fbf807684ae1944592aa169f38d/source/web_hooks.rst#whitelisting-talkable-ips

2024-11-27 12:49 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +1. Navigate into the App store:
```suggestion
1. Navigate to the App store:
```

2024-11-27 12:49 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +2. Choose an `Custom app` and clicking “Install”
```suggestion
2. Choose a `Custom app` and clicking “Install”
```

2024-11-27 12:49 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +-----------------
```suggestion
-----------------

```

2024-11-27 12:49 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +^^^^^^^^^^^^^^^
Please use syntax from the README for headers and subheaders:
https://github.com/talkable/talkable-docs?tab=readme-ov-file#cross-referencing

Please also leave an empty line after all headers.

2024-11-28 10:58 UTC, zhuravel requested changes

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +    :alt: App store step 2
```suggestion
  .. image:: /_static/img/email_marketing_and_automation/app_store_step_2.png
     :alt: App store step 2
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
I’m following indentation guidelines from RST documentation.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html

```suggestion
   const crypto = require('crypto');
 
   const WEBHOOK_SECRET_KEY = 'my_webhook_secret';
 
   function verifyWebhook(data, headerSignature) {
     // Calculate HMAC
     const calculatedSignature = btoa(crypto
       .createHmac('sha256', WEBHOOK_SECRET_KEY)
       .update(data)
       .digest('hex')
     );
 
     return crypto.timingSafeEqual(
       Buffer.from(calculatedSignature, 'base64'),
       Buffer.from(headerSignature, 'base64')
     );
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  :alt: Send same payload
One issue here is indentation, but the ALT text is not clear to me — what does "Send some payload" mean here? Should it say variables?
```suggestion
   :alt: Variables
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
I’m following indentation guidelines from RST documentation.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html

```suggestion
   {
     "site_id": "1",
     "campaign_id": "142",
     "referral_status": "in_progress",
     "advocate_email": "advocate@example.com",
     "friend_email": "friend@example.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "email": "person-9eb230f8d189fca9@talkable-sample.com",
     "email_optin": "true",
     "phone_number": "+12025551111",
     "phone_optin": "true"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "person-40728a5b940e3247@talkable-sample.com",
     "email_optin": "true"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "person-fa8e880e25bd47b3@talkable-sample.com",
     "phone_number": "+12025551111"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "loyalty@talkable.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "loyalty@talkable.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "person-591542c54ff21a49@talkable-sample.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "email": "person-591542c54ff21a49@talkable-sample.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "description": "$5",
     "amount": "5.0",
     "coupon_code": "FR_NEW_5_OFF",
     "reason": "click",
     "site_id": "1"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "coupon_code": "SAMPLE-COUPON-CODE",
     "coupon_discount_amount": "0.0"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "type": "Event",
     "created_at": "2024-11-25 00:00:00 -0800",
     "event_category": "public_event",
     "event_number": "183247241",
     "subtotal": "100.0",
     "currency_iso_code": "USD",
     "email": "advocate@example.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  }
```suggestion
   {
     "site_id": "1",
     "campaign_id": "142",
     "referral_status": "in_progress",
     "advocate_email": "advocate@example.com",
     "friend_email": "friend@example.com"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +
```suggestion
   {
     "email": "friend@example.com",
     "site_id": "1"
   }
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +2. Open your Custom app .
Redundant space.
```suggestion
2. Open your Custom app.
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  :columns: 4
```suggestion
   :columns: 4
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +  .. include:: /partials/talkable_ip_list.rst
```suggestion
   .. include:: /partials/talkable_ip_list.rst
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +When referral has been created this action sends you information.
```suggestion
Triggers when a new referral is created, sending detailed information about the referral.
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +      :alt: Send same payload
> [!IMPORTANT]  
> Please don’t forget to rename the image file.

* Fix indentation.
* Fix file name, "same payload" is a typo and does not make sense in this context.

```suggestion
  .. image:: /_static/img/email_marketing_and_automation/send_sample_payload.png
     :alt: Send sample payload
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +When referral has been created this action sends you information.
This text seems to be copy-paste from "Referral Create" without a proper change.
```suggestion
This action is triggered when referral’s status changes.
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +When Event or Purchase have been registered this actions sends you information.
```suggestion
Triggers when a new event or purchase is created.
```

2024-11-28 10:58 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +Whenever a person shares the offer the share information will be sent to your ESP.
```suggestion
Whenever a person shares the offer, the share information will be sent to your ESP.
```

2024-12-03 14:34 UTC, zhuravel commented
@wrimer Yes and yes. Thank you!

2024-12-03 14:38 UTC, zhuravel requested changes

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +   :alt: Send same payload
This should either say "Send **sample** payload" or "Variables" (as it refers to image other than `send_sample_payload.png`)

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +Sync email opt ins
You don’t have a space in `signups` above but have in `opt ins`.
Please use either signups / optins or sign ups / opt ins consistently.

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +Referral Status Change
```suggestion
Referral status change
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/custom_app.rst
> +Offer Share
```suggestion
Offer share
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/hubspot.rst
>      :alt: Send same payload
```suggestion
    :alt: Send sample payload
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/klaviyo.rst
>      :alt: Send same payload
```suggestion
    :alt: Send sample payload
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/mailchimp.rst
>      :alt: Send same payload
```suggestion
    :alt: Send sample payload
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/oracle_bronto.rst
>      :alt: Send same payload
```suggestion
    :alt: Send sample payload
```

2024-12-03 14:38 UTC, zhuravel commented on source/email_marketing_and_automation/sailthru.rst
>      :alt: Send same payload
```suggestion
    :alt: Send sample payload
```

2024-12-03 20:49 UTC, wrimer commented
@zhuravel chatGPT says that `sign ups/signups` and `opt-ins/optins` pairs should be used in different cases. So, i altered description with his suggestions. 
![CleanShot 2024-12-03 at 22 44 34@2x](https://github.com/user-attachments/assets/f30b8c0b-56c2-4687-a048-2b7ec0585af7)
Also I've added this point for [task for our product manifest](https://talkable.atlassian.net/browse/PR-23488)
For history: Task for reviewing indentation: https://talkable.atlassian.net/browse/PR-23489

2024-12-04 00:15 UTC, zhuravel approved these changes

2024-12-10 08:25 UTC, merged